#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Update all packages
#?? 1.0.0
##?
##? Usage:
##?    update_all

docs::eval_help "$@"

echo '🍎 Updating Ubuntu packages'
sudo apt update
sudo apt upgrade

echo ''
echo '⚡️ ZSH Zim'
zsh ${ZIM_HOME}/zimfw.zsh upgrade
zsh ${ZIM_HOME}/zimfw.zsh update
zsh ${ZIM_HOME}/zimfw.zsh uninstall & zsh ${ZIM_HOME}/zimfw.zsh install
