#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Update all git projects
#?? 1.0.0
##?
##? Usage:
##?    update_projects

flowsredrepositories="/home/dtome/Workspace/sred/moodle
/home/dtome/Workspace/sred/next/moodle"

for flowsredrepository in $flowsredrepositories;
do
  cd $flowsredrepository
  git stash clear
  git add . && git stash save
  git reload
  has_content=$(git stash list)
  if [ -z "$has_content"  ];
  then
    echo "No changes to apply"
  else
    git stash apply -q
    echo "     🔋 Stash changes applied to repository"
  fi

  echo ''
  echo "👌 $flowsredrepository updated"
  echo 'Done!'
done

repositories="/home/dtome/Workspace/sred/meta"

for repository in $repositories;
do
  cd $repository
  git stash clear
  git add . && git stash save
  git remote update && git rebase origin/master
  has_content=$(git stash list)
  if [ -z "$has_content"  ];
  then
    echo "No changes to apply"
  else
    git stash apply -q
    echo "     🔋 Stash changes applied to repository"
  fi

  echo ''
  echo "👌 $repository updated"
  echo 'Done!'
done
